version: "3.4"
services:
  threshold-pre-client.public.dappnode.eth:
    build: .
    image: "threshold-pre-client.public.dappnode.eth:0.1.0"
    restart: unless-stopped
    ports:
      - "9151:9151"
    volumes:
      - "nucypher:/root/.local/share/nucypher"
      - "ethereum:/root/.ethereum"
volumes:
  nucypher: {}
  ethereum: {}
